name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  Warp_Chrome:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.11'
          environment-file: environment.yml
          activate-environment: chrome-automation
          auto-activate-base: false

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Install Python Dependencies
        run: |
          conda info
          conda list
          python -m pip install --upgrade pip
          python -m playwright install

      - name: Build Chrome Package
        run: python run.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: build/release/*
          retention-days: 15

      - name: Build Package Folder
        run: |
          mkdir -p build/package
          cp -r build/release/application build/package/
          cp environment.yml *.py README.md build/package/
          cd build
          zip -r release.zip package

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: github.event_name != 'pull_request'
        with:
          name: Playwright Chrome Kit Release - v1.0.${{ github.run_number }}
          tag_name: playwright-chrome-kit-v1.0.${{ github.run_number }}
          files: build/release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        permissions:
          contents: write
