name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  Warp_Chrome:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # 确保 conda 环境正确激活
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.11'
          environment-file: environment.yml
          activate-environment: chrome-automation
          auto-activate-base: false

      - name: Install Dependencies
        run: |
          conda info
          conda list
          python -m pip install --upgrade pip
          python -m playwright install

      - name: Build Chrome Package
        run: python run.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: build/release/*
          retention-days: 15
